# Generated by Django 4.2.4 on 2023-08-08 13:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.RenameField(
            model_name="quizscore",
            old_name="status",
            new_name="status_pass",
        ),
    ]
