# Generated by Django 4.2.4 on 2023-08-08 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0005_alter_quizassignment_options_alter_student_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizassignment",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.DeleteModel(
            name="Student",
        ),
    ]
