# Generated by Django 4.2.4 on 2023-08-08 19:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_alter_quizassignment_student_delete_student"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quizassignment",
            name="questions",
        ),
    ]
