# Generated by Django 4.2.4 on 2023-08-10 13:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0011_remove_quiz_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="students",
            field=models.ManyToManyField(
                related_name="students_quizzes", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
