# Generated by Django 4.2.4 on 2023-08-10 13:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0012_quiz_students"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="quiz",
            name="students",
        ),
    ]
