# Generated by Django 4.2.4 on 2023-08-10 13:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0013_remove_quiz_students"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="quiz_type",
            field=models.CharField(
                choices=[
                    ("MULTIPLE", "Multiple"),
                    ("SHORT", "Short"),
                    ("TRUEFALSE", "TrueFalse"),
                ],
                default="Short",
                max_length=128,
            ),
        ),
    ]
