# Generated by Django 4.2.4 on 2023-08-10 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0014_quiz_quiz_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="quiz",
            name="students",
            field=models.ManyToManyField(
                related_name="assigned_quizzes",
                through="base.QuizAssignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
