# Generated by Django 4.2.4 on 2023-08-11 05:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0019_classroomstudentenrolled_enrolled"),
    ]

    operations = [
        migrations.AddField(
            model_name="classroom",
            name="name",
            field=models.CharField(default="Class 1", max_length=128),
        ),
    ]
