# Generated by Django 4.2.4 on 2023-08-11 06:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0022_quizassignment_classroom"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="classroom",
            name="quizzes",
        ),
        migrations.DeleteModel(
            name="ClassroomQuizHistory",
        ),
    ]
