# Generated by Django 4.2.4 on 2023-08-11 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0025_alter_quiz_classroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quizassignment",
            name="classroom",
            field=models.ForeignKey(
                default=4,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.classroom",
            ),
        ),
    ]
