# Generated by Django 4.2.4 on 2023-08-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0026_alter_quizassignment_classroom"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_options",
            field=models.CharField(
                choices=[
                    ("MULTIPLE", "Multiple"),
                    ("SHORT", "Short"),
                    ("TRUEFALSE", "TrueFalse"),
                ],
                default="Short",
                max_length=255,
            ),
        ),
    ]
