# Generated by Django 4.2.4 on 2023-08-11 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0028_quiz_last_date_alter_question_answer_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="last_date",
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
