# Generated by Django 4.2.4 on 2023-08-16 05:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0030_remove_quiz_last_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.classroom"
            ),
        ),
        migrations.AlterField(
            model_name="quiz",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_quizzes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="quizassignment",
            name="classroom",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="base.classroom"
            ),
        ),
    ]
