# Generated by Django 4.2.4 on 2023-08-21 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0031_alter_quiz_classroom_alter_quiz_teacher_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593934)
            ),
        ),
        migrations.AddField(
            model_name="answer",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593947)
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593934)
            ),
        ),
        migrations.AddField(
            model_name="classroom",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593947)
            ),
        ),
        migrations.AddField(
            model_name="classroomstudentenrolled",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593934)
            ),
        ),
        migrations.AddField(
            model_name="classroomstudentenrolled",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593947)
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593934)
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593947)
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593934)
            ),
        ),
        migrations.AddField(
            model_name="quiz",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593947)
            ),
        ),
        migrations.AddField(
            model_name="quizassignment",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593934)
            ),
        ),
        migrations.AddField(
            model_name="quizassignment",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593947)
            ),
        ),
        migrations.AddField(
            model_name="quizscore",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593934)
            ),
        ),
        migrations.AddField(
            model_name="quizscore",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 593947)
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 594109)
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="updated_at",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 8, 21, 10, 49, 53, 594115)
            ),
        ),
    ]
