# Generated by Django 4.2.4 on 2023-08-17 05:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0031_alter_quiz_classroom_alter_quiz_teacher_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question",
            name="answer_options",
            field=models.CharField(
                choices=[("SHORT", "Short"), ("TRUEFALSE", "TrueFalse")],
                default="Short",
                max_length=255,
            ),
        ),
    ]
