# Generated by Django 4.2.4 on 2023-08-21 13:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0033_alter_answer_created_at_alter_answer_updated_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="answer",
            name="created",
        ),
        migrations.RemoveField(
            model_name="classroom",
            name="created",
        ),
        migrations.RemoveField(
            model_name="classroomstudentenrolled",
            name="created",
        ),
        migrations.RemoveField(
            model_name="quiz",
            name="created",
        ),
        migrations.RemoveField(
            model_name="quizscore",
            name="timestamp",
        ),
    ]
