# Generated by Django 4.2.4 on 2023-08-21 13:57

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0033_alter_question_answer_options"),
        ("base", "0034_remove_answer_created_remove_classroom_created_and_more"),
    ]

    operations = []
